### ISSUE TITLE
Snappy

### ISSUE THREAD

**Issue by brontide** [jk-5/unifi-inform-protocol#3]
Yes, it was used for snappy for a while, I have captures and a working decoder for flags = 5 ( encryption + snappy ).  The compression seems to be depreciated and they are back to zlib and moved on to GCM.

**Comment by jeffreykog** [comment]
Thanks for your comment. So 0x04 is now always zlib instead of snappy? Or is the combination 0x01 & 0x04 zlib + GCM?

**Comment by brontide** [comment]
No, 0x04 = snappy and 0x02 is always zlib.  It seems like when they switched from CBC to GCM they dropped using snappy.  I'm not sure exactly when they started and stopped using snappy but 0x04 seems pretty dead these days.

0x09 = Encrypted with GCM ( for short payloads )
0x0B ~~0x11~~ = Encrypted with GCM and zlib compressed

In the old captures I have it was often 0x05 = Encrypted and snappy compressed.  I've never seen snappy and GCM but it's possible I just never had the right combo.  I'm actually wondering if it was dropped in the 3.x->4.x firmware shuffle.

Been doing a deep dive on inform and adoption, working on a proxy to do various debugging and testing.

**Comment by jeffreykog** [comment]
Okay clear. I will update it in my protocol overview and add the comment that Snappy is probably obsolete in favour of zlib. Chances are big they did the conversion to zlib and to AES-GCM at once. Thanks again!
